services:
  elasticsearch:
    image: opensearchproject/opensearch:2.14.0
    mem_limit: 1700m
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: opensearchproject/opensearch-dashboards:2.14.0
    mem_limit: 256m
    environment:
      - 'OPENSEARCH_HOSTS=["http://elasticsearch:9200"]'
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
